flags:
    hgeometry:
        examples: true
        interactive: true
packages:
- '.'
extra-deps:
- reactive-banana-gi-gtk-0.2.0.0
- gtk2hs-buildtools-0.13.2.2
- cairo-canvas-0.1.0.0
- vinyl-0.6.0
- approximate-equality-1.1.0.2
- type-level-natural-number-2.0
build:
  # library-profiling: true
  # executable-profiling: true
extra-lib-dirs:
  - /usr/lib/
resolver: lts-9.0
