flags:
    hgeometry:
        examples: true
        interactive: false
packages:
- '.'
extra-deps: []
build:
  # library-profiling: true
  # executable-profiling: true
extra-lib-dirs:
- /opt/local/
resolver: lts-10.3
