flags:
    hgeometry:
        examples: true
        interactive: false
packages:
- '.'
extra-deps:
- approximate-equality-1.1.0.2
- type-level-natural-number-2.0
- multiset-0.3.4.1
build:
  # library-profiling: true
  # executable-profiling: true
extra-lib-dirs:
- /usr/lib
#resolver: lts-10.3
resolver: nightly-2018-05-25
